#pragma config(Sensor, in1,    sensor,         sensorPotentiometer)
#pragma config(Motor,  port10,          Rdrive2,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int potentiometer = SensorValue[sensor];
task main()
{
	while(1==1)
	{
			motor[port10]=vexRT[Ch2]/2;
	}
	if(vexRT[Ch2]==0)
	{
			motor[port10]=0;
	}
	if(vexRT[Ch3]==0)
	{
			motor[port10]=0;
	}
	if(vexRT[Btn7U]==1)
{
	while(potentiometer < 2000 )
{
		motor[port10]=127;
	}
	while(potentiometer > 2000)
	{
		motor[port10]=-127;
	}
	}
}
